version: "3"
services:
  db:
    image: mysql:5.7
    container_name: db
    command:
      --default-authentication-plugin=mysql_native_password
    volumes:
      - dbfile:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3307:3307"

  server_php_apache:
    build: images/php-apache
    container_name: php_apache
    command:
      --with-included-apr
    volumes:
      - ./src:/var/www/html
      - ./conf/apache/apache2.conf:/etc/apache2/apache2.conf
      - ./logs/apache:/var/log/apache2
    depends_on:
      - db

  server_nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./src:/var/www/html
      - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
    ports:
      - "80:80"
    depends_on:
      - server_php_apache

volumes:
    dbfile: